version: "3.4"
services:
  eth1-fallback:
    image: ${ETH1_FALLBACK_IMAGE}
    container_name: ${COMPOSE_PROJECT_NAME}_eth1-fallback
    restart: unless-stopped
    stop_grace_period: 3m
    volumes:
      - eth1fallbackclientdata:/ethclient
      - ./chains/eth1:/setup:ro
    networks:
      - net
    environment:
      - CLIENT=${ETH1_FALLBACK_CLIENT}
      - ETHSTATS_LABEL=${FALLBACK_ETHSTATS_LABEL}
      - ETHSTATS_LOGIN=${FALLBACK_ETHSTATS_LOGIN}
      - INFURA_PROJECT_ID=${FALLBACK_INFURA_PROJECT_ID}
      - POCKET_PROJECT_ID=${FALLBACK_POCKET_PROJECT_ID}
      - HTTP_PROVIDER_URL=${FALLBACK_HTTP_PROVIDER_URL}
      - WS_PROVIDER_URL=${FALLBACK_WS_PROVIDER_URL}
      - ETH1_P2P_PORT=${FALLBACK_ETH1_P2P_PORT}
    entrypoint: sh
    command: "/setup/start-node.sh"
    cap_drop:
      - all
    cap_add:
      - dac_override
    security_opt:
      - no-new-privileges
networks:
  net:
volumes:
  eth1fallbackclientdata: